services:
  kafka:
    image: apache/kafka:4.0.0
    hostname: kafka
    container_name: kafka
    networks:
      - my_network
    ports:
      - 9092:9092
    environment:
      # Configures Kafka to run in KRaft mode with a specific cluster ID
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      # You can generate a random UUID for this, or use a standard one like below:
      KAFKA_CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    networks:
      - my_network
    depends_on:
      - kafka
    ports:
      - 8090:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      # This links Kafka UI to your Kafka service over the shared network
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

networks:
  my_network:
    driver: bridge