---
version: '2'
services:
  kafka:
    image: apache/kafka:4.0.0
    hostname: kafka
    container_name: kafka
    networks:
      - my_network
    ports:
      - 9092:9092
    #environment:
      #KAFKA_BROKER_ID: 1
      #KAfka_CLUSTER_ID:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    networks:
      - my_network
    depends_on:
      - kafka
    ports:
      - 8090:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
networks:
  my_network:
    driver: bridge